language: ruby

rvm:
  - 2.1.2

env:
  - TRAVIS_TEST_ENV=1

before_install:
  - sudo apt-get install python-virtualenv
install:
  - ./setup_travis.sh
before_script:
  - venv/bin/python manage.py migrate
  - ./init_database_travis.sh
  - venv/bin/python manage.py runserver 0.0.0.0:8000 &
  - sleep 3 # Give web server some time to start
script:
  - venv/bin/python manage.py test
  - ./functional_tests/runall.sh
notifications:
  email:
    recipients:
      - ngthanhtrung23@gmail.com
    on_success: change
    on_failure: always
