language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
script: python manage.py test
notifications:
  email:
    recipients:
      - chequochuu@yahoo.com.vn
      - other@example.com
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always
